/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AirdropInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTokens"
      | "burn"
      | "claimReferralReward"
      | "codeToReferrer"
      | "emergencyWithdraw"
      | "generateReferralCode"
      | "getMyReferralCode"
      | "getMyReferralCount"
      | "getReferralCode"
      | "hasParticipated"
      | "owner"
      | "pendingReferrals"
      | "refereeReward"
      | "referralCount"
      | "referrerReward"
      | "registerReferral"
      | "renounceOwnership"
      | "requiredStakeAmount"
      | "stakingContract"
      | "token"
      | "transferOwnership"
      | "updateRefereeReward"
      | "updateReferrerReward"
      | "updateRequiredStakeAmount"
      | "usedReferralCodes"
      | "userReferralCode"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReferralCodeGenerated"
      | "ReferralRewardClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimReferralReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "codeToReferrer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generateReferralCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyReferralCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyReferralCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralCode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasParticipated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingReferrals",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refereeReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referrerReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerReferral",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredStakeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRefereeReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReferrerReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRequiredStakeAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usedReferralCodes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userReferralCode",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReferralReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "codeToReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyReferralCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasParticipated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReferrals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refereeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referrerReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredStakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRefereeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReferrerReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRequiredStakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedReferralCodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userReferralCode",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralCodeGeneratedEvent {
  export type InputTuple = [user: AddressLike, code: BytesLike];
  export type OutputTuple = [user: string, code: string];
  export interface OutputObject {
    user: string;
    code: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardClaimedEvent {
  export type InputTuple = [referrer: AddressLike, referee: AddressLike];
  export type OutputTuple = [referrer: string, referee: string];
  export interface OutputObject {
    referrer: string;
    referee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Airdrop extends BaseContract {
  connect(runner?: ContractRunner | null): Airdrop;
  waitForDeployment(): Promise<this>;

  interface: AirdropInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTokens: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  burn: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  claimReferralReward: TypedContractMethod<
    [referee: AddressLike],
    [void],
    "nonpayable"
  >;

  codeToReferrer: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  generateReferralCode: TypedContractMethod<[], [void], "nonpayable">;

  getMyReferralCode: TypedContractMethod<[], [string], "view">;

  getMyReferralCount: TypedContractMethod<[], [bigint], "view">;

  getReferralCode: TypedContractMethod<[user: AddressLike], [string], "view">;

  hasParticipated: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingReferrals: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  refereeReward: TypedContractMethod<[], [bigint], "view">;

  referralCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  referrerReward: TypedContractMethod<[], [bigint], "view">;

  registerReferral: TypedContractMethod<
    [referralCode: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requiredStakeAmount: TypedContractMethod<[], [bigint], "view">;

  stakingContract: TypedContractMethod<[], [string], "view">;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRefereeReward: TypedContractMethod<
    [_newAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateReferrerReward: TypedContractMethod<
    [_newAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRequiredStakeAmount: TypedContractMethod<
    [_newAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  usedReferralCodes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  userReferralCode: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReferralReward"
  ): TypedContractMethod<[referee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "codeToReferrer"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "generateReferralCode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMyReferralCode"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyReferralCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReferralCode"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasParticipated"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingReferrals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "refereeReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "referralCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "referrerReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerReferral"
  ): TypedContractMethod<[referralCode: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredStakeAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRefereeReward"
  ): TypedContractMethod<[_newAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReferrerReward"
  ): TypedContractMethod<[_newAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRequiredStakeAmount"
  ): TypedContractMethod<[_newAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedReferralCodes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "userReferralCode"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReferralCodeGenerated"
  ): TypedContractEvent<
    ReferralCodeGeneratedEvent.InputTuple,
    ReferralCodeGeneratedEvent.OutputTuple,
    ReferralCodeGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewardClaimed"
  ): TypedContractEvent<
    ReferralRewardClaimedEvent.InputTuple,
    ReferralRewardClaimedEvent.OutputTuple,
    ReferralRewardClaimedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReferralCodeGenerated(address,bytes32)": TypedContractEvent<
      ReferralCodeGeneratedEvent.InputTuple,
      ReferralCodeGeneratedEvent.OutputTuple,
      ReferralCodeGeneratedEvent.OutputObject
    >;
    ReferralCodeGenerated: TypedContractEvent<
      ReferralCodeGeneratedEvent.InputTuple,
      ReferralCodeGeneratedEvent.OutputTuple,
      ReferralCodeGeneratedEvent.OutputObject
    >;

    "ReferralRewardClaimed(address,address)": TypedContractEvent<
      ReferralRewardClaimedEvent.InputTuple,
      ReferralRewardClaimedEvent.OutputTuple,
      ReferralRewardClaimedEvent.OutputObject
    >;
    ReferralRewardClaimed: TypedContractEvent<
      ReferralRewardClaimedEvent.InputTuple,
      ReferralRewardClaimedEvent.OutputTuple,
      ReferralRewardClaimedEvent.OutputObject
    >;
  };
}
