/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { Airdrop } from "./Airdrop";
export type { LiquidityVault } from "./LiquidityVault";
export type { Presale } from "./Presale";
export type { Staking } from "./Staking";
export type { Swap } from "./Swap";
export type { Token } from "./Token";
