/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PresaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRICE_INCREASE_INTERVAL"
      | "PRICE_INCREASE_PERCENTAGE"
      | "TOKENS_FOR_LIQUIDITY_PERCENTAGE"
      | "claimRefund"
      | "contributions"
      | "emergencyStop"
      | "finalize"
      | "getCurrentPrice"
      | "getTokensForBNB"
      | "initialPrice"
      | "lastCalculatedPrice"
      | "lastPriceCalculationTime"
      | "liquidityVault"
      | "maxContribution"
      | "owner"
      | "pancakeRouter"
      | "participate"
      | "presaleFinalized"
      | "presaleStartTime"
      | "renounceOwnership"
      | "setInitialPrice"
      | "setMaxContribution"
      | "stakingContract"
      | "toggleEmergencyStop"
      | "token"
      | "totalRaised"
      | "totalTokensSold"
      | "transferOwnership"
      | "withdrawAccumulatedEth"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyToggled"
      | "EthWithdrawn"
      | "MaxContributionUpdated"
      | "OwnershipTransferred"
      | "PresaleFinalized"
      | "RemainingTokensStaked"
      | "TokensPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PRICE_INCREASE_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_INCREASE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKENS_FOR_LIQUIDITY_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyStop",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "finalize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensForBNB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastCalculatedPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPriceCalculationTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxContribution",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pancakeRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleFinalized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setInitialPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxContribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleEmergencyStop",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalRaised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokensSold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAccumulatedEth",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PRICE_INCREASE_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_INCREASE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKENS_FOR_LIQUIDITY_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensForBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCalculatedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPriceCalculationTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pancakeRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInitialPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleEmergencyStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokensSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAccumulatedEth",
    data: BytesLike
  ): Result;
}

export namespace EmergencyToggledEvent {
  export type InputTuple = [stopped: boolean];
  export type OutputTuple = [stopped: boolean];
  export interface OutputObject {
    stopped: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthWithdrawnEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxContributionUpdatedEvent {
  export type InputTuple = [newMax: BigNumberish];
  export type OutputTuple = [newMax: bigint];
  export interface OutputObject {
    newMax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresaleFinalizedEvent {
  export type InputTuple = [ethAmount: BigNumberish, tokenAmount: BigNumberish];
  export type OutputTuple = [ethAmount: bigint, tokenAmount: bigint];
  export interface OutputObject {
    ethAmount: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemainingTokensStakedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    ethAmount: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    ethAmount: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    buyer: string;
    ethAmount: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Presale extends BaseContract {
  connect(runner?: ContractRunner | null): Presale;
  waitForDeployment(): Promise<this>;

  interface: PresaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRICE_INCREASE_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  PRICE_INCREASE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  TOKENS_FOR_LIQUIDITY_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  claimRefund: TypedContractMethod<[], [void], "nonpayable">;

  contributions: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  emergencyStop: TypedContractMethod<[], [boolean], "view">;

  finalize: TypedContractMethod<[], [void], "nonpayable">;

  getCurrentPrice: TypedContractMethod<[], [bigint], "view">;

  getTokensForBNB: TypedContractMethod<
    [bnbAmount: BigNumberish],
    [bigint],
    "view"
  >;

  initialPrice: TypedContractMethod<[], [bigint], "view">;

  lastCalculatedPrice: TypedContractMethod<[], [bigint], "view">;

  lastPriceCalculationTime: TypedContractMethod<[], [bigint], "view">;

  liquidityVault: TypedContractMethod<[], [string], "view">;

  maxContribution: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pancakeRouter: TypedContractMethod<[], [string], "view">;

  participate: TypedContractMethod<[], [void], "payable">;

  presaleFinalized: TypedContractMethod<[], [boolean], "view">;

  presaleStartTime: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setInitialPrice: TypedContractMethod<
    [_newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxContribution: TypedContractMethod<
    [_newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakingContract: TypedContractMethod<[], [string], "view">;

  toggleEmergencyStop: TypedContractMethod<[], [void], "nonpayable">;

  token: TypedContractMethod<[], [string], "view">;

  totalRaised: TypedContractMethod<[], [bigint], "view">;

  totalTokensSold: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawAccumulatedEth: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRICE_INCREASE_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_INCREASE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKENS_FOR_LIQUIDITY_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyStop"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "finalize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokensForBNB"
  ): TypedContractMethod<[bnbAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastCalculatedPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastPriceCalculationTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidityVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxContribution"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pancakeRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participate"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "presaleFinalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "presaleStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInitialPrice"
  ): TypedContractMethod<[_newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxContribution"
  ): TypedContractMethod<[_newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "toggleEmergencyStop"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalRaised"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTokensSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawAccumulatedEth"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EmergencyToggled"
  ): TypedContractEvent<
    EmergencyToggledEvent.InputTuple,
    EmergencyToggledEvent.OutputTuple,
    EmergencyToggledEvent.OutputObject
  >;
  getEvent(
    key: "EthWithdrawn"
  ): TypedContractEvent<
    EthWithdrawnEvent.InputTuple,
    EthWithdrawnEvent.OutputTuple,
    EthWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MaxContributionUpdated"
  ): TypedContractEvent<
    MaxContributionUpdatedEvent.InputTuple,
    MaxContributionUpdatedEvent.OutputTuple,
    MaxContributionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PresaleFinalized"
  ): TypedContractEvent<
    PresaleFinalizedEvent.InputTuple,
    PresaleFinalizedEvent.OutputTuple,
    PresaleFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "RemainingTokensStaked"
  ): TypedContractEvent<
    RemainingTokensStakedEvent.InputTuple,
    RemainingTokensStakedEvent.OutputTuple,
    RemainingTokensStakedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;

  filters: {
    "EmergencyToggled(bool)": TypedContractEvent<
      EmergencyToggledEvent.InputTuple,
      EmergencyToggledEvent.OutputTuple,
      EmergencyToggledEvent.OutputObject
    >;
    EmergencyToggled: TypedContractEvent<
      EmergencyToggledEvent.InputTuple,
      EmergencyToggledEvent.OutputTuple,
      EmergencyToggledEvent.OutputObject
    >;

    "EthWithdrawn(uint256)": TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;
    EthWithdrawn: TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;

    "MaxContributionUpdated(uint256)": TypedContractEvent<
      MaxContributionUpdatedEvent.InputTuple,
      MaxContributionUpdatedEvent.OutputTuple,
      MaxContributionUpdatedEvent.OutputObject
    >;
    MaxContributionUpdated: TypedContractEvent<
      MaxContributionUpdatedEvent.InputTuple,
      MaxContributionUpdatedEvent.OutputTuple,
      MaxContributionUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PresaleFinalized(uint256,uint256)": TypedContractEvent<
      PresaleFinalizedEvent.InputTuple,
      PresaleFinalizedEvent.OutputTuple,
      PresaleFinalizedEvent.OutputObject
    >;
    PresaleFinalized: TypedContractEvent<
      PresaleFinalizedEvent.InputTuple,
      PresaleFinalizedEvent.OutputTuple,
      PresaleFinalizedEvent.OutputObject
    >;

    "RemainingTokensStaked(uint256)": TypedContractEvent<
      RemainingTokensStakedEvent.InputTuple,
      RemainingTokensStakedEvent.OutputTuple,
      RemainingTokensStakedEvent.OutputObject
    >;
    RemainingTokensStaked: TypedContractEvent<
      RemainingTokensStakedEvent.InputTuple,
      RemainingTokensStakedEvent.OutputTuple,
      RemainingTokensStakedEvent.OutputObject
    >;

    "TokensPurchased(address,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
  };
}
