/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockUniswapV2Router02,
  MockUniswapV2Router02Interface,
} from "../../../contracts/mocks/MockUniswapV2Router02";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ethAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "LiquidityAdded",
    type: "event",
  },
  {
    inputs: [],
    name: "WETH",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenDesired",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "addLiquidityETH",
    outputs: [
      {
        internalType: "uint256",
        name: "amountToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061028c806100206000396000f3fe6080604052600436106100385760003560e01c8063ad5c464814610044578063c45a015514610084578063f305d719146100ab57600080fd5b3661003f57005b600080fd5b34801561005057600080fd5b5073c02aaa39b223fe8d0a0e5c4f27ead9083c756cc25b6040516001600160a01b0390911681526020015b60405180910390f35b34801561009057600080fd5b50735c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f610067565b6100be6100b93660046101d5565b6100d9565b6040805193845260208401929092529082015260600161007b565b6040516323b872dd60e01b815233600482015230602482015260448101869052600090819081906001600160a01b038a16906323b872dd906064016020604051808303816000875af1158015610133573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190610157919061022d565b50604080516001600160a01b038b81168252602082018b905234828401528716606082015290517f3c69701a61c79a92ef9692903aaa0068bce8771361ecb09547391e4fb4df85379181900360800190a1509597349750889650945050505050565b80356001600160a01b03811681146101d057600080fd5b919050565b60008060008060008060c087890312156101ee57600080fd5b6101f7876101b9565b955060208701359450604087013593506060870135925061021a608088016101b9565b915060a087013590509295509295509295565b60006020828403121561023f57600080fd5b8151801515811461024f57600080fd5b939250505056fea2646970667358221220e66f26666ef1f87faf7a6f037b662f6a27962afb633a0e33d9d16de81f55f88864736f6c63430008130033";

type MockUniswapV2Router02ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockUniswapV2Router02ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockUniswapV2Router02__factory extends ContractFactory {
  constructor(...args: MockUniswapV2Router02ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockUniswapV2Router02 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockUniswapV2Router02__factory {
    return super.connect(runner) as MockUniswapV2Router02__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockUniswapV2Router02Interface {
    return new Interface(_abi) as MockUniswapV2Router02Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockUniswapV2Router02 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockUniswapV2Router02;
  }
}
